SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+03:30";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mvc`
--

-- Check and drop/create 'messages' table
DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Subject` VARCHAR(45) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  `Email` VARCHAR(128) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  `Body` VARCHAR(245) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_persian_ci;

-- Check and drop/create 'users' table
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  `lastname` VARCHAR(50) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  `email` VARCHAR(64) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  `password` VARCHAR(512) COLLATE utf8mb4_persian_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_persian_ci;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
